export const NEPAL_STATES = [
  {
    name: 'Koshi Province',
    cities: [
      'Biratnagar',
      'Itahari',
      'Dharan',
      'Bhadrapur',
      'Mechinagar',
      'Damak',
      'Rajbiraj',
      'Inaruwa',
      'Birtamod',
      'Dhankuta',
      'Kankai',
      'Bhojpur',
      'Terhathum',
      'Panchthar',
      'Ilam',
      'Jhapa',
      'Morang',
      'Sunsari',
      'Saptari',
      'Udayapur',
    ],
  },
  {
    name: 'Madhesh Province',
    cities: [
      'Janakpur',
      'Birgunj',
      'Kalaiya',
      'Gaur',
      'Malangwa',
      'Jaleshwar',
      'Bardibas',
      'Siraha',
      'Lahan',
      'Dhanusha',
      'Mahottari',
      'Sarlahi',
      'Rautahat',
      'Bara',
      'Parsa',
    ],
  },
  {
    name: 'Bagmati Province',
    cities: [
      'Kathmandu',
      'Lalitpur',
      'Bhaktapur',
      'Hetauda',
      'Bharatpur',
      'Banepa',
      'Dhulikhel',
      'Panauti',
      'Bidur',
      'Chautara',
      'Kamalamai',
      'Manthali',
      'Bhimeshwar',
      'Kavrepalanchok',
      'Dhading',
      'Nuwakot',
      'Rasuwa',
      'Sindhupalchok',
      'Dolakha',
      'Ramechhap',
      'Sindhuli',
      'Makwanpur',
      'Chitwan',
    ],
  },
  {
    name: 'Gandaki Province',
    cities: [
      'Pokhara',
      'Baglung',
      'Beni',
      'Kawasoti',
      'Besishahar',
      'Gorkha',
      'Damauli',
      'Kaski',
      'Tanahun',
      'Syangja',
      'Lamjung',
      'Myagdi',
      'Mustang',
      'Manang',
      'Nawalpur',
      'Parbat',
    ],
  },
  {
    name: 'Lumbini Province',
    cities: [
      'Butwal',
      'Bhairahawa (Siddharthanagar)',
      'Nepalgunj',
      'Kohalpur',
      'Tansen',
      'Gorahi',
      'Tulsipur',
      'Taulihawa',
      'Sunwal',
      'Bardaghat',
      'Rupandehi',
      'Kapilvastu',
      'Dang',
      'Banke',
      'Bardiya',
      'Palpa',
      'Arghakhanchi',
      'Gulmi',
      'Pyuthan',
      'Rolpa',
      'Eastern Rukum',
      'Parasi',
    ],
  },
  {
    name: 'Karnali Province',
    cities: [
      'Birendranagar (Surkhet)',
      'Jumla',
      'Dailekh',
      'Dunai',
      'Manma',
      'Gamgadhi',
      'Simikot',
      'Salyan',
      'Surkhet',
      'Jajarkot',
      'Western Rukum',
      'Kalikot',
      'Mugu',
      'Humla',
      'Dolpa',
    ],
  },
  {
    name: 'Sudurpashchim Province',
    cities: [
      'Dhangadhi',
      'Bhimdatta (Mahendranagar)',
      'Tikapur',
      'Attariya (Godawari)',
      'Dadeldhura',
      'Dipayal Silgadhi',
      'Amargadhi',
      'Kailali',
      'Kanchanpur',
      'Doti',
      'Achham',
      'Bajhang',
      'Bajura',
      'Darchula',
      'Baitadi',
      'Jogbudha',
    ],
  },
];
