import { User, GraduationCap, BookOpen, Clock } from "lucide-react";

export const NEPAL_STATES = [
  {
    name: "Koshi Province",
    cities: [
      "Biratnagar",
      "Itahari",
      "Dharan",
      "Bhadrapur",
      "Mechinagar",
      "Damak",
      "Rajbiraj",
      "Inaruwa",
      "Birtamod",
      "Dhankuta",
      "Kankai",
      "Bhojpur",
      "Terhathum",
      "Panchthar",
      "Ilam",
      "Jhapa",
      "Morang",
      "Sunsari",
      "Saptari",
      "Udayapur",
    ],
  },
  {
    name: "Madhesh Province",
    cities: [
      "Janakpur",
      "Birgunj",
      "Kalaiya",
      "Gaur",
      "Malangwa",
      "Jaleshwar",
      "Bardibas",
      "Siraha",
      "Lahan",
      "Dhanusha",
      "Mahottari",
      "Sarlahi",
      "Rautahat",
      "Bara",
      "Parsa",
    ],
  },
  {
    name: "Bagmati Province",
    cities: [
      "Kathmandu",
      "Lalitpur",
      "Bhaktapur",
      "Hetauda",
      "Bharatpur",
      "Dhulikhel",
      "Banepa",
      "Panauti",
      "Kirtipur",
      "Madhyapur Thimi",
      "Budhanilkantha",
      "Gokarneshwar",
      "Chandragiri",
      "Tokha",
      "Suryabinayak",
      "Nagarkot",
      "Dhading",
      "Nuwakot",
      "Rasuwa",
      "Sindhupalchok",
      "Dolakha",
      "Ramechhap",
      "Sindhuli",
      "Makwanpur",
      "Chitwan",
    ],
  },
  {
    name: "Gandaki Province",
    cities: [
      "Pokhara",
      "Gorkha",
      "Lekhnath",
      "Kusma",
      "Baglung",
      "Besisahar",
      "Damauli",
      "Waling",
      "Beni",
      "Jomsom",
      "Kawasoti",
      "Gaindakot",
      "Putalibazar",
      "Syangja",
      "Chapakot",
      "Galyang",
      "Ramgram",
    ],
  },
  {
    name: "Lumbini Province",
    cities: [
      "Butwal",
      "Nepalgunj",
      "Tansen",
      "Gulariya",
      "Banganga",
      "Shivaraj",
      "Kapilvastu",
      "Buddhabhumi",
      "Sandhikharka",
      "Tamghas",
      "Pyuthan",
      "Salyan",
      "Rolpa",
      "Rukum",
      "Dang",
      "Banke",
      "Bardiya",
    ],
  },
  {
    name: "Karnali Province",
    cities: [
      "Birendranagar",
      "Manma",
      "Jumla",
      "Dunai",
      "Chandannath",
      "Mahabu",
      "Thuli Bheri",
      "Narayan",
      "Bheri",
      "Chhedagad",
      "Aathbiskot",
      "Musikot",
      "Chhayanath",
      "Tribeni",
    ],
  },
  {
    name: "Sudurpashchim Province",
    cities: [
      "Dhangadhi",
      "Mahendranagar",
      "Tikapur",
      "Ghodaghodi",
      "Lamki Chuha",
      "Bhimdatta",
      "Punarbas",
      "Belauri",
      "Amargadhi",
      "Dasharathchand",
      "Melauli",
      "Purchaudi",
      "Jogbudha",
    ],
  },
];

export const FORM_STEPS = [
  {
    number: 1,
    title: "Basic Info",
    description: "Personal details",
    icon: User,
  },
  {
    number: 2,
    title: "Qualifications",
    description: "Education & subjects",
    icon: GraduationCap,
  },
  {
    number: 3,
    title: "Teaching Details",
    description: "Experience & bio",
    icon: BookOpen,
  },
  {
    number: 4,
    title: "Availability",
    description: "Schedule setup",
    icon: Clock,
  },
];
