export const formatExperience = (years) => {
  if (years === 0) return "No experience";
  if (years === 1) return "1 year";
  return `${years} years`;
};

export const formatAvailability = (availability) => {
  if (!availability || availability.length === 0) return "Not specified";

  return availability
    .map(
      (item) =>
        `${item.day}: ${item.timeSlots
          .map((slot) => `${slot.start} - ${slot.end}`)
          .join(", ")}`
    )
    .join("; ");
};

export const generateAvatarUrl = (publicId) => {
  if (!publicId) return "/default-avatar.png";
  // This would be generated by Cloudinary on the backend
  return `https://res.cloudinary.com/${process.env.REACT_APP_CLOUDINARY_CLOUD_NAME}/image/upload/w_500,h_500,c_fill,q_auto,f_webp/${publicId}`;
};

export const generateCVUrl = (publicId) => {
  if (!publicId) return null;
  return `https://res.cloudinary.com/${process.env.REACT_APP_CLOUDINARY_CLOUD_NAME}/raw/upload/${publicId}`;
};

export const validateFile = (file, maxSize, allowedTypes) => {
  if (file.size > maxSize) {
    return `File size must be less than ${maxSize / (1024 * 1024)}MB`;
  }

  if (!allowedTypes.includes(file.type)) {
    return `File type must be ${allowedTypes.join(", ")}`;
  }

  return null;
};
